### ISSUE TITLE
Feedback style

### ISSUE THREAD

**Issue by roberrrt-s** [Choerd/frontend-data#3]
Hi Sjoerd,
Mooie code, ik ben wel geintrigeerd door je inmiddels best wel substantiele verzameling scripts.js. Het idee van git en github is dat je met version control niet dit soort bestanden hoeft aan te maken, doordat je in de history van je commits terug kan kijken en deze kan rollbacken if necessary.  Je cleaningData.js file is zeg maar het type file waar ik als programmeur blij van wordt, probeer zoveel mogelijk die standaard aan te houden. Als je dit echter importeert kun je het beter wel een wat betekenisvollere naam dan 'functie' geven.  Bijv. `import clean from './modules/cleaningData.js'`.
Verder lekker op weg, veel succes deze week

**Comment by Choerd** [comment]
De grote hoeveelheid aan script.js bestanden was inderdaad om mijn proces van mijn update pattern bij te kunnen houden! bedankt voor je feedback
