### ISSUE TITLE
Feedback Repository

### ISSUE THREAD

**Issue by StefanGerrits2** [Choerd/frontend-data#4]
## Algemeen
* Goed dat je al een live link hebt.
* Description zou ik in het engels doen.

## Readme
Je nog je hele readme schrijven, denk aan het volgende;
* Afbeelding concept
* Concept uitleg
* Links naar gebruikte voorbeelden voor je d3 code
* Iets over je SparQL query

## Wiki

* Leg je concept uit in een aparte pagina; denk hierbij aan de legenda en titel
* Er zijn nog geen pagina's over je update pattern en functional pattern, deze moet je uiteraard niet vergeten.

**Comment by Choerd** [comment]
allemaal verwerkt, bedankt voor je feedback
