### ISSUE TITLE
Feedback Concept

### ISSUE THREAD

**Issue by StefanGerrits2** [Choerd/frontend-data#5]
* Lastig om in één oogopslag te weten welke materialen het populairst zijn, nu moet je hiervoor eerst over heen hoveren met je muis. Tekst labels zou eventueel een oplossing kunnen zijn, of een legenda op kleur.

* Degene die het bekijkt leert over hoeveel objecten er zijn per land?  Daarna over welke materialen daar het vaakst voorkomen? Hier moet ik nu eerst zelf achter komen. Een introductie tekst of legenda zou dit op kunnen lossen.

* Naar mijn idee geen specifieke doelgroep gekozen (weet niet of dit per sé moet)

* De data die veranderd zijn de bubbels die groter, kleiner, of zelfs verwijderd worden met behulp van transities. Dit ziet er leuk en speels uit.

**Comment by Choerd** [comment]
- Tekstlabels toegevoegd aan grote landen en veelvoorkomende materialen
- Introductie heb ik niet meer snel kunnen maken
- Doelgroep bepaald
